services:
  database:
    image: postgres:16.3
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  web:
    build: 
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/code:rw
    command: npm run start:dev
    depends_on:
      - database
  web-debug:
    build: 
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/code:rw
    command: sleep infinity
    depends_on:
      - database